# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

dotenv: [.env]

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  install:
    desc: install
    aliases: [i]
    run: once
    sources:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    cmds:
      - pnpm install
      - pnpm approve-builds

  clean:
    desc: clean
    silent: true
    cmds:
      - rm -rf dist
      - rm -rf coverage

  clean-hard:
    desc: clean hard
    cmds:
      - task: clean
      - rm -rf node_modules/

  dev:
    desc: run as dev
    cmds:
      - task: install
      - pnpm --silent run dev

  lint:
    desc: lint
    aliases: [l]
    cmds:
      - task: install
      - pnpm --silent run lint
