services:
  client:
    build:
      context: ./client
    ports:
      - 3000:80
    environment:
      NODE_ENV: production

  server:
    build:
      context: ./server
    ports:
      - 3001:3000
    environment:
      NODE_ENV: production
      PORT: 3000